import 'package:wolfera/common/enums/car_makers.dart';

/// Canonical dataset of car models grouped by maker.
/// Extend freely as needed. Keep names as commonly used marketing names.
class CarModelsData {
  static const Map<CarMaker, List<String>> modelsByMaker = {
    CarMaker.bmw: [
      '1 Series',
      '2 Series',
      '3 Series',
      '4 Series',
      '5 Series',
      '6 Series',
      '7 Series',
      '8 Series',
      'X1',
      'X2',
      'X3',
      'X4',
      'X5',
      'X6',
      'X7',
      'Z4',
      'i3',
      'i4',
      'i5',
      'i7',
      'iX',
      'M2',
      'M3',
      'M4',
      'M5',
      'M8',
    ],
    CarMaker.mercedes: [
      'A-Class',
      'B-Class',
      'C-Class',
      'E-Class',
      'S-Class',
      'CLA',
      'CLS',
      'CLE',
      'SL',
      'SLC',
      'GLA',
      'GLB',
      'GLC',
      'GLE',
      'GLS',
      'G-Class',
      'V-Class',
      'EQA',
      'EQB',
      'EQC',
      'EQE',
      'EQS',
      'AMG GT',
    ],
    CarMaker.audi: [
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'Q2',
      'Q3',
      'Q4 e-tron',
      'Q5',
      'Q7',
      'Q8',
      'TT',
      'R8',
      'e-tron',
      'e-tron GT',
    ],
    CarMaker.volkswagen: [
      'Up',
      'Polo',
      'Golf',
      'Jetta',
      'Bora',
      'Passat',
      'Arteon',
      'T-Cross',
      'T-Roc',
      'Taos',
      'Tiguan',
      'Touareg',
      'Teramont',
      'Atlas',
      'Caddy',
      'Transporter',
      'ID.3',
      'ID.4',
      'ID.5',
      'ID. Buzz',
    ],
    CarMaker.jeep: [
      'Renegade',
      'Compass',
      'Cherokee',
      'Grand Cherokee',
      'Grand Cherokee L',
      'Wrangler',
      'Gladiator',
      'Commander',
      'Wagoneer',
      'Grand Wagoneer',
    ],
    CarMaker.toyota: [
      'Yaris',
      'Corolla',
      'Corolla Cross',
      'Camry',
      'Avalon',
      'Crown',
      'Supra',
      'GR86',
      'C-HR',
      'RAV4',
      'Highlander',
      '4Runner',
      'FJ Cruiser',
      'Land Cruiser',
      'Prado',
      'Fortuner',
      'Hilux',
      'Tacoma',
      'Tundra',
      'Sequoia',
      'Sienna',
      'Prius',
      'bZ4X',
    ],
    CarMaker.kia: [
      'Picanto',
      'Rio',
      'Cerato',
      'Forte',
      'Ceed',
      'Optima',
      'K3',
      'K5',
      'K8',
      'K9',
      'Stinger',
      'Soul',
      'Seltos',
      'Stonic',
      'Sportage',
      'Sorento',
      'Telluride',
      'Carnival',
      'Carens',
      'Niro',
      'EV3',
      'EV5',
      'EV6',
      'EV9',
    ],
    CarMaker.ford: [
      'Fiesta',
      'Focus',
      'Fusion',
      'Mondeo',
      'Taurus',
      'Mustang',
      'EcoSport',
      'Puma',
      'Kuga',
      'Escape',
      'Edge',
      'Explorer',
      'Expedition',
      'Bronco',
      'Ranger',
      'Maverick',
      'F-150',
      'Super Duty',
      'Transit',
    ],
    CarMaker.hyundai: [
      'i10',
      'i20',
      'i30',
      'Accent',
      'Elantra',
      'Avante',
      'Sonata',
      'Azera',
      'Grandeur',
      'Veloster',
      'Venue',
      'Bayon',
      'Creta',
      'Kona',
      'Tucson',
      'Santa Fe',
      'Palisade',
      'Staria',
      'H-1',
      'Ioniq',
      'Ioniq 5',
      'Ioniq 6',
    ],
    CarMaker.honda: [
      'City',
      'Civic',
      'Accord',
      'Insight',
      'Jazz',
      'Fit',
      'HR-V',
      'ZR-V',
      'CR-V',
      'Pilot',
      'Passport',
      'Odyssey',
      'Ridgeline',
    ],
    CarMaker.porsche: [
      '718 Boxster',
      '718 Cayman',
      '911',
      'Panamera',
      'Macan',
      'Cayenne',
      'Taycan',
    ],
    CarMaker.rollsRoyce: [
      'Phantom',
      'Ghost',
      'Wraith',
      'Dawn',
      'Cullinan',
      'Spectre',
    ],
    CarMaker.tesla: [
      'Model 3',
      'Model S',
      'Model X',
      'Model Y',
      'Cybertruck',
      'Roadster',
    ],
    CarMaker.bentley: [
      'Continental GT',
      'Flying Spur',
      'Bentayga',
      'Mulsanne',
      'Azure',
      'Brooklands',
    ],
    CarMaker.ferrari: [
      '488',
      'F8 Tributo',
      'Roma',
      'Portofino',
      'California',
      '812 Superfast',
      '296 GTB',
      'SF90 Stradale',
      'Purosangue',
      'LaFerrari',
    ],
    CarMaker.lamborghini: [
      'Aventador',
      'Huracan',
      'Gallardo',
      'Urus',
      'Revuelto',
      'Murcielago',
    ],
    CarMaker.nissan: [
      'Micra',
      'Sunny',
      'Versa',
      'Sentra',
      'Altima',
      'Maxima',
      'Leaf',
      'Juke',
      'Kicks',
      'Qashqai',
      'X-Trail',
      'Rogue',
      'Murano',
      'Pathfinder',
      'Armada',
      'Patrol',
      'Navara',
      'Titan',
      'GT-R',
      '370Z',
      'Z',
    ],
    CarMaker.landrover: [
      'Defender',
      'Discovery',
      'Discovery Sport',
      'Range Rover',
      'Range Rover Sport',
      'Range Rover Velar',
      'Range Rover Evoque',
      'Freelander',
    ],
    CarMaker.lexus: [
      'CT',
      'IS',
      'ES',
      'GS',
      'LS',
      'UX',
      'NX',
      'RX',
      'GX',
      'LX',
      'RC',
      'LC',
      'RZ',
    ],
    CarMaker.bugatti: [
      'Veyron',
      'Chiron',
      'Divo',
      'Centodieci',
      'Mistral',
      'Tourbillon',
    ],
    CarMaker.infiniti: [
      'Q30',
      'Q50',
      'Q60',
      'Q70',
      'QX30',
      'QX50',
      'QX55',
      'QX60',
      'QX70',
      'QX80',
    ],
    CarMaker.dacia: [
      'Sandero',
      'Logan',
      'Duster',
      'Jogger',
      'Lodgy',
      'Dokker',
      'Spring',
    ],
    CarMaker.skoda: [
      'Citigo',
      'Fabia',
      'Rapid',
      'Scala',
      'Octavia',
      'Superb',
      'Kamiq',
      'Karoq',
      'Kodiaq',
      'Enyaq',
    ],
    CarMaker.subaru: [
      'Impreza',
      'Legacy',
      'WRX',
      'BRZ',
      'XV',
      'Crosstrek',
      'Forester',
      'Outback',
      'Ascent',
      'Solterra',
    ],
    CarMaker.mitsubishi: [
      'Mirage',
      'Attrage',
      'Lancer',
      'Galant',
      'ASX',
      'Eclipse Cross',
      'Outlander',
      'Pajero',
      'Montero',
      'L200',
      'Triton',
      'Xpander',
    ],
    CarMaker.maserati: [
      'Ghibli',
      'Quattroporte',
      'GranTurismo',
      'GranCabrio',
      'Levante',
      'Grecale',
      'MC20',
    ],
    CarMaker.mazda: [
      'Mazda2',
      'Mazda3',
      'Mazda6',
      'MX-5',
      'CX-3',
      'CX-30',
      'CX-5',
      'CX-50',
      'CX-60',
      'CX-70',
      'CX-80',
      'CX-9',
      'CX-90',
      'BT-50',
      'RX-8',
    ],
    CarMaker.alfaromeo: [
      'MiTo',
      'Giulietta',
      'Giulia',
      'Stelvio',
      'Tonale',
      '4C',
    ],
    CarMaker.astonMartin: [
      'Vantage',
      'DB9',
      'DB11',
      'DB12',
      'DBS',
      'Rapide',
      'Vanquish',
      'Valhalla',
      'DBX',
    ],
    CarMaker.cadillac: [
      'ATS',
      'CTS',
      'CT4',
      'CT5',
      'CT6',
      'XTS',
      'XT4',
      'XT5',
      'XT6',
      'SRX',
      'Escalade',
      'Lyriq',
    ],
    CarMaker.chevrolet: [
      'Spark',
      'Aveo',
      'Sonic',
      'Cruze',
      'Malibu',
      'Impala',
      'Camaro',
      'Corvette',
      'Trax',
      'Tracker',
      'Trailblazer',
      'Equinox',
      'Traverse',
      'Blazer',
      'Tahoe',
      'Suburban',
      'Colorado',
      'Silverado',
    ],
    CarMaker.citroen: [
      'C1',
      'C2',
      'C3',
      'C3 Aircross',
      'C4',
      'C4 Cactus',
      'C5',
      'C5 Aircross',
      'Berlingo',
      'Jumpy',
      'Jumper',
    ],
    CarMaker.cupra: [
      'Born',
      'Formentor',
      'Leon',
      'Ateca',
      'Tavascan',
      'Terramar',
    ],
    CarMaker.daewoo: [
      'Matiz',
      'Lanos',
      'Nubira',
      'Lacetti',
      'Leganza',
      'Kalos',
      'Tacuma',
    ],
    CarMaker.fiat: [
      '500',
      '500X',
      '500L',
      'Panda',
      'Punto',
      'Tipo',
      'Linea',
      'Bravo',
      'Doblo',
      'Fiorino',
      'Ducato',
    ],
    CarMaker.isuzu: [
      'D-Max',
      'MU-X',
      'Trooper',
      'Rodeo',
      'N-Series',
      'F-Series',
    ],
    CarMaker.iveco: [
      'Daily',
      'Eurocargo',
      'S-Way',
      'Stralis',
      'Trakker',
    ],
    CarMaker.koenigsegg: [
      'CCX',
      'Agera',
      'Regera',
      'Jesko',
      'Gemera',
      'One:1',
    ],
    CarMaker.lada: [
      'Granta',
      'Vesta',
      'Niva',
      'XRAY',
      'Largus',
      'Priora',
      'Kalina',
      'Samara',
    ],
    CarMaker.man: [
      'TGE',
      'TGL',
      'TGM',
      'TGS',
      'TGX',
      'Lion\'s Coach',
    ],
    CarMaker.mclaren: [
      '540C',
      '570S',
      '600LT',
      '650S',
      '720S',
      '750S',
      'Artura',
      'GT',
      'P1',
      'Senna',
    ],
    CarMaker.mg: [
      '3',
      '4',
      '5',
      '6',
      '7',
      'GT',
      'HS',
      'RX5',
      'ZS',
      'Marvel R',
      'Cyberster',
    ],
    CarMaker.mini: [
      'Cooper',
      'Cooper S',
      'Clubman',
      'Countryman',
      'Paceman',
      'Coupe',
      'Roadster',
      'Convertible',
    ],
    CarMaker.opel: [
      'Adam',
      'Karl',
      'Corsa',
      'Astra',
      'Vectra',
      'Insignia',
      'Crossland',
      'Mokka',
      'Grandland',
      'Zafira',
      'Combo',
    ],
    CarMaker.peugeot: [
      '107',
      '108',
      '206',
      '207',
      '208',
      '301',
      '307',
      '308',
      '408',
      '508',
      '2008',
      '3008',
      '5008',
      'Partner',
      'Rifter',
      'Traveller',
    ],
    CarMaker.pontiac: [
      'G3',
      'G5',
      'G6',
      'G8',
      'Grand Am',
      'Grand Prix',
      'Firebird',
      'GTO',
      'Solstice',
      'Vibe',
    ],
    CarMaker.seat: [
      'Mii',
      'Ibiza',
      'Leon',
      'Toledo',
      'Cordoba',
      'Altea',
      'Arona',
      'Ateca',
      'Tarraco',
      'Alhambra',
    ],
    CarMaker.smart: [
      'Fortwo',
      'Forfour',
      'Roadster',
      '#1',
      '#3',
    ],
    CarMaker.suzuki: [
      'Alto',
      'Celerio',
      'Swift',
      'Baleno',
      'Dzire',
      'Ciaz',
      'Ignis',
      'Vitara',
      'Grand Vitara',
      'S-Cross',
      'Jimny',
      'Ertiga',
    ],
    CarMaker.togg: [
      'T10X',
      'T10F',
    ],
    CarMaker.volvo: [
      'S40',
      'S60',
      'S80',
      'S90',
      'V40',
      'V60',
      'V90',
      'XC40',
      'XC60',
      'XC70',
      'XC90',
      'EX30',
      'EX90',
      'C40',
    ],
  };

  /// Returns models for a single maker.
  static List<String> forMaker(CarMaker maker) =>
      List.unmodifiable(modelsByMaker[maker] ?? const <String>[]);

  /// Returns a de-duplicated union of models for a list of makers.
  static List<String> forMakers(Iterable<CarMaker> makers) {
    final set = <String>{};
    for (final m in makers) {
      final list = modelsByMaker[m];
      if (list != null) set.addAll(list);
    }
    final res = set.toList();
    res.sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
    return res;
  }
}
